---
# Some files to load in, and store data
Pedestal_file: python/alibava/Data/ped_0V
Delay_scan: ''
Charge_scan: python/alibava/Data/calibration_0V
Measurement_file: python/alibava/Data/RSrun_0V

Save_output: True # General flag for saving the plots and so on
Output_folder: python/alibava/Alibava_Plots/ #Specify an existing folder,can't mkdir
Output_name: "0V_test" #revise
#Pickle_output: pickleData # Possible option are JSON, pickle
isBinary: False # If the files provided are Alibava binaries (True) or hdf5 (False) file types
use_charge_cal: True
#Gain_params: [220, 0] # if use_charge_cal == False then these parameters will be used for the gain calc
plot_config_file: plot_cfg.yml # relative path to the plot config file

# Event analysis parameters
Charge_scale: False # Convert ADC to electrons
Processes: 1 # High numbers of processes causes huge memory overhead, only use when more than 100G are available for large files!!!
SN_cut: 6 # Minimum height of hit
SN_ratio: 0.3 # Ratio at which the program searches for nearby hits below the SN cut,SN_ratio*SN_cut=neigh_cut
SN_cluster: 3.5 # SN what the whole cluster must have at minimum to be considered, values great then 7 are useless (seed cut) #经过S/N cut和Neigh cut后确定cluster size，再计算cluster内strip的平均信噪比
Noise_cut: 2. # Here the unit is ADC over median of all strips. This discriminates noisy strips.
Manual_mask: [] # Manual channel masking
Chips: [1,2] # Alibava Chip selection (Alibava has 2 chips with each 128 channels)
numChan: 256
timingWindow:
  - 9 # Minimum timing window
  - 22 # Maximum timing window
max_cluster_size: 7 # Directly affects runtime!!!
sensor_type: "n-in-p" # Sensor Material
calibrate_gain_to: negative # parameters to calibrate the gain pulses to a specific polarity, options are negative, positive, both
automasking: True # Tries to find non physical or garbage hits (wrong ADC direction) and excludes them from calculation (costs moderate CPU)
optimize: False # Use Numba jit optimizer or not --> Warning no progress bar can be shown with this true, or may be misleading
charge_cal_polynom: 3 #2 Degree of poly to fit at charge cal curves
range_ADC_fit: [70,250] # range in which will be fitted in ADC if you pass an empty list all data will be used

additional_analysis:
    - Langau
    #- CCE
    #- ChargeSharing
    #- PositionResolution
    

Langau:
  clustersize: [1,2,3,4] # Defines which cluster sizes should be fitted with a langau, list of values defines only these, negative values are for all clustersizes
  numClus: [1,2] # Define which/how many clusters per event are taken into account for calculations
  seed_cut_langau: True # If you want a langau from the seed cut strips only or not
  energyCutOff: 500 # Define where the high energy cutoff is applied in electrons or ADC
  bins: 100 # Define how many bins the Langau plots should have
  fitLangau: True # Fit a langau or not (sometimes the data does not represent a langau at all)
  Charge_scale: False # Convert ADC to electrons
  ClusterCut: 0.5 # Cut from maximum height of langau, at which the fit will start for cluster Langau
  SCCut: 0.33 # Cut from maximum height of langau, at which the fit will start for SC langau


PositionResolution:
  pitch: 100 # um
  SavGol: True # Use the Savitzky-Golay filter to smooth out the input array
  SavGol_params: [21,2] # [Window_size (odd number), order]
  SavGol_iter: 30 # Iterations of the filter

ChargeSharing:
  clustersize: [1,2,3,4]
  numClus: [1,2]

CCE:
  clustersize: [1,2,3,4]
